name : amitech
include:
 - ../amitech-be/docker-compose.yaml
services:
  load_balancer:
    image: nginx:alpine
    container_name: load_balancer
    ports:
      - 80:80
      - 8081:8081
    depends_on:
       web_server:
         condition : service_started
    networks:
      - ami-net
    volumes:
      - ./nginx-server.conf:/etc/nginx/conf.d/default.conf
  web_server:
    build: .
    networks:
      - ami-net
    volumes:  
      - ./nginx-webserver.conf:/etc/nginx/conf.d/default.conf 
    deploy:
      replicas : 2
    depends_on:
      strapi:
        condition: service_started
        restart : true
networks:
  ami-net:
    external : true
